"""Admin usage analytics aggregates."""


async def _signup(client):
    await client.post("/api/auth/setup", json={"username": "alice", "password": "hunter22hunter"})


async def _send(client, cid, text):
    async with client.stream(
        "POST", f"/api/conversations/{cid}/messages", json={"content": text}
    ) as r:
        assert r.status_code == 200, await r.aread()
        async for _ in r.aiter_bytes():
            pass


async def test_analytics_aggregates(client):
    await _signup(client)  # alice (admin) -> 1 user
    cid = (await client.post("/api/conversations", json={"model": None})).json()["id"]
    await _send(client, cid, "hello")  # user + assistant
    await _send(client, cid, "again")  # user + assistant  => 4 messages

    msgs = (await client.get(f"/api/conversations/{cid}")).json()["messages"]
    assistant = [m for m in msgs if m["role"] == "assistant"][-1]
    await client.put(
        f"/api/conversations/{cid}/messages/{assistant['id']}/feedback", json={"rating": 1}
    )
    await client.post("/api/channels", json={"name": "general"})

    a = (await client.get("/api/admin/analytics")).json()
    assert a["totals"] == {"users": 1, "conversations": 1, "messages": 4, "channels": 1}
    assert a["feedback"] == {"up": 1, "down": 0}
    assert a["active_users_7d"] == 1
    assert a["new_users_7d"] == 1
    assert len(a["messages_per_day"]) == 30  # default window, zero-filled
    assert sum(d["count"] for d in a["messages_per_day"]) == 4  # all sent today
    # The conversation picked no model, so each reply was generated by (and now
    # records) the resolved default model; 2 assistant msgs bucket under it.
    models = {m["model"]: m["count"] for m in a["messages_per_model"]}
    assert models == {"llama3.2": 2}


async def test_analytics_excludes_inactive_variants(client, upstream):
    """Regenerate keeps the superseded reply as active=0; analytics counts only
    the active (user-visible) messages."""
    from tests.conftest import content_chunk, finish, sse

    await _signup(client)
    cid = (await client.post("/api/conversations", json={"model": None})).json()["id"]
    await _send(client, cid, "hi")  # u1 + a1 (both active) -> 2 visible
    upstream.queue_chat(sse(content_chunk("take two"), finish("stop")))
    async with client.stream("POST", f"/api/conversations/{cid}/regenerate", json={}) as r:
        assert r.status_code == 200
        async for _ in r.aiter_bytes():
            pass
    # table now has u1(active), a1(active=0), a2(active=1) = 3 rows, 2 visible
    a = (await client.get("/api/admin/analytics")).json()
    assert a["totals"]["messages"] == 2  # the archived variant is excluded
    models = {m["model"]: m["count"] for m in a["messages_per_model"]}
    assert models == {"llama3.2": 1}  # one active assistant (resolved default), not two
    assert sum(d["count"] for d in a["messages_per_day"]) == 2


async def test_analytics_days_window(client):
    await _signup(client)
    assert len((await client.get("/api/admin/analytics?days=7")).json()["messages_per_day"]) == 7
    assert (await client.get("/api/admin/analytics?days=0")).status_code == 422
    assert (await client.get("/api/admin/analytics?days=999")).status_code == 422


async def test_analytics_admin_only(client):
    await _signup(client)
    await client.post(
        "/api/admin/users", json={"username": "bob", "password": "passpass", "role": "user"}
    )
    await client.post("/api/auth/logout")
    await client.post("/api/auth/login", json={"username": "bob", "password": "passpass"})
    assert (await client.get("/api/admin/analytics")).status_code == 403


async def test_analytics_requires_auth(client):
    assert (await client.get("/api/admin/analytics")).status_code == 401


def _usage_chunk(p, c):
    return {"choices": [], "usage": {"prompt_tokens": p, "completion_tokens": c, "total_tokens": p + c}}


async def test_token_usage_captured_and_aggregated(client, upstream):
    from tests.conftest import content_chunk, finish, sse

    await _signup(client)
    cid = (await client.post("/api/conversations", json={})).json()["id"]
    upstream.queue_chat(sse(content_chunk("hi there"), finish("stop"), _usage_chunk(12, 5)))
    await _send(client, cid, "hello")

    a = (await client.get("/api/admin/analytics")).json()
    assert a["tokens"] == {"prompt": 12, "completion": 5, "total": 17}
    assert a["cost_total"] is None  # no prices configured
    assert any(v["total_tokens"] == 17 for v in a["tokens_per_model"])

    # the counts are persisted on the assistant message
    msgs = (await client.get(f"/api/conversations/{cid}")).json()["messages"]
    asst = [m for m in msgs if m["role"] == "assistant"][-1]
    # not exposed on StoredMessage, but the analytics SUM proves they're stored
    assert asst["content"] == "hi there"


async def test_token_usage_sums_across_tool_loop(client, upstream):
    from tests.conftest import content_chunk, finish, sse, tool_call_chunk

    await _signup(client)
    cid = (await client.post("/api/conversations", json={})).json()["id"]
    await client.patch(f"/api/conversations/{cid}", json={"tools_enabled": True})
    # first upstream call (tool request) reports usage, second (final answer) too
    upstream.queue_chat(
        sse(tool_call_chunk("calculate", '{"expression":"1+1"}'), finish("tool_calls"), _usage_chunk(10, 3)),
        sse(content_chunk("it is 2"), finish("stop"), _usage_chunk(20, 7)),
    )
    await _send(client, cid, "1+1?")

    a = (await client.get("/api/admin/analytics")).json()
    # summed across both upstream calls: 10+20 prompt, 3+7 completion
    assert a["tokens"] == {"prompt": 30, "completion": 10, "total": 40}


async def test_cost_computed_from_prices(client, upstream, monkeypatch):
    from app.config import settings
    from tests.conftest import content_chunk, finish, sse

    await _signup(client)
    cid = (await client.post("/api/conversations", json={})).json()["id"]
    await client.patch(f"/api/conversations/{cid}", json={"model": "priced-model"})
    monkeypatch.setattr(settings, "model_prices", {"priced-model": {"input": 1.0, "output": 2.0}})
    upstream.queue_chat(
        sse(content_chunk("answer"), finish("stop"), _usage_chunk(2_000_000, 1_000_000))
    )
    await _send(client, cid, "q")

    a = (await client.get("/api/admin/analytics")).json()
    # 2M input @ $1/1M + 1M output @ $2/1M = 2 + 2 = 4.0
    assert a["cost_total"] == 4.0
    row = next(m for m in a["tokens_per_model"] if m["model"] == "priced-model")
    assert row["cost"] == 4.0
