"""Postgres connection-pool backend: real per-request transactions + per-task
connection isolation. Skipped unless FREE_WEBUI_TEST_DATABASE_URL points at a
Postgres (the dual-backend CI sets it); the SQLite path is covered by
test_database.py."""
import asyncio
import os

import pytest

PG_URL = os.environ.get("FREE_WEBUI_TEST_DATABASE_URL")
pytestmark = pytest.mark.skipif(
    not PG_URL, reason="requires Postgres (set FREE_WEBUI_TEST_DATABASE_URL)"
)


async def _pool_db():
    import asyncpg

    from app.database import PostgresDatabase

    pool = await asyncpg.create_pool(PG_URL, min_size=2, max_size=5)
    db = PostgresDatabase(pool)
    await db.execute("DROP TABLE IF EXISTS pooltest")
    await db.execute(
        "CREATE TABLE pooltest (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT)"
    )
    return db


async def test_pg_transaction_commits():
    db = await _pool_db()
    try:
        async with db.transaction():
            await db.insert("INSERT INTO pooltest (name) VALUES (?)", ("a",))
            await db.insert("INSERT INTO pooltest (name) VALUES (?)", ("b",))
        assert await db.fetch_val("SELECT COUNT(*) FROM pooltest") == 2
    finally:
        await db.execute("DROP TABLE IF EXISTS pooltest")
        await db.close()


async def test_pg_transaction_rolls_back_and_does_not_leak():
    db = await _pool_db()
    try:
        await db.insert("INSERT INTO pooltest (name) VALUES (?)", ("seed",))

        class Boom(Exception):
            pass

        with pytest.raises(Boom):
            async with db.transaction():
                await db.insert("INSERT INTO pooltest (name) VALUES (?)", ("ghost",))
                raise Boom()

        # ghost was rolled back (a real BEGIN/ROLLBACK, not the old autocommit no-op)
        assert await db.fetch_val("SELECT COUNT(*) FROM pooltest") == 1
        # ...and the rolled-back write can't leak into a later autocommit statement
        await db.insert("INSERT INTO pooltest (name) VALUES (?)", ("real",))
        names = [r[0] for r in await db.fetch_all("SELECT name FROM pooltest ORDER BY id")]
        assert names == ["seed", "real"]
    finally:
        await db.execute("DROP TABLE IF EXISTS pooltest")
        await db.close()


async def test_pg_concurrent_transactions_isolated():
    """Two transactions on separate tasks each bind their own pooled connection
    (contextvar-local), so they overlap concurrently and both commit — they don't
    serialize behind one shared connection, and one's BEGIN doesn't bleed into the
    other. (On a single shared connection asyncpg would error on the overlap.)"""
    db = await _pool_db()
    try:
        async def worker(name: str):
            async with db.transaction():
                await db.insert("INSERT INTO pooltest (name) VALUES (?)", (name,))
                await asyncio.sleep(0.05)  # force the two transactions to overlap

        await asyncio.gather(worker("x"), worker("y"))
        names = sorted(r[0] for r in await db.fetch_all("SELECT name FROM pooltest"))
        assert names == ["x", "y"]
    finally:
        await db.execute("DROP TABLE IF EXISTS pooltest")
        await db.close()


async def test_pg_concurrent_ops_inside_one_transaction_raise():
    """Using the bound connection from another task (a gather of db ops, or a
    db-touching child task) inside one transaction() must fail LOUDLY rather than
    corrupt the shared asyncpg connection."""
    db = await _pool_db()
    try:
        with pytest.raises(RuntimeError, match="concurrent"):
            async with db.transaction():
                await asyncio.gather(
                    db.execute("INSERT INTO pooltest (name) VALUES (?)", ("a",)),
                    db.execute("INSERT INTO pooltest (name) VALUES (?)", ("b",)),
                )
    finally:
        await db.execute("DROP TABLE IF EXISTS pooltest")
        await db.close()
