"""Backend-agnostic database boundary (Phase 1 of docs/SCALING.md).

The whole app talks to a ``Database`` instead of a raw connection. Two backends
implement the same small interface:

* ``Database`` — SQLite via aiosqlite (the zero-config default). A transparent
  proxy: ``execute`` returns the real aiosqlite cursor and ``__getattr__``
  forwards anything not wrapped, so existing call sites are unchanged.
* ``PostgresDatabase`` — Postgres via asyncpg (opt-in via a ``postgresql://``
  URL). Backed by an ``asyncpg`` connection **pool**: a statement outside a
  transaction acquires a connection for that one statement (autocommit, like
  before), while ``transaction()`` acquires ONE pooled connection, binds it to
  the current task via a ``ContextVar`` so every ``execute`` inside the block
  hits it, and runs a real ``BEGIN/COMMIT/ROLLBACK`` — so multi-statement
  mutations are genuinely atomic, and concurrent requests no longer serialize
  behind a single shared connection. ``execute`` translates ``?``→``$N`` and
  buffers rows behind a cursor shim exposing ``fetchone``/``fetchall``.

Dialect-specific SQL the call sites still emit (``strftime``, ``GROUP_CONCAT``,
``COLLATE NOCASE``, …) is normalized per-backend in :func:`adapt_query`; DDL is
normalized in :func:`to_pg_ddl`.
"""
from __future__ import annotations

import asyncio
import contextvars
import re
import sqlite3
from contextlib import asynccontextmanager
from typing import Any

import aiosqlite

Row = Any  # tuple-like row (positional indexing), for both backends

# Backend-neutral integrity-violation exception types (UNIQUE / FK / check), so
# `except INTEGRITY_ERRORS` recovers identically on both backends. aiosqlite's
# IntegrityError IS sqlite3.IntegrityError; asyncpg raises (a subclass of)
# IntegrityConstraintViolationError, which is NOT a sqlite3 exception.
INTEGRITY_ERRORS: tuple = (sqlite3.IntegrityError,)
try:  # asyncpg is optional (only installed for the Postgres backend)
    import asyncpg as _asyncpg

    INTEGRITY_ERRORS = (
        sqlite3.IntegrityError,
        _asyncpg.exceptions.IntegrityConstraintViolationError,
    )
except ImportError:
    pass


# ---- query / DDL adaptation -------------------------------------------------

def qmark_to_dollar(sql: str) -> str:
    """Rewrite ``?`` placeholders to Postgres ``$1, $2, …`` (skips quoted text)."""
    out: list[str] = []
    n = 0
    in_str = False
    for ch in sql:
        if ch == "'":
            in_str = not in_str
            out.append(ch)
        elif ch == "?" and not in_str:
            n += 1
            out.append(f"${n}")
        else:
            out.append(ch)
    return "".join(out)


def adapt_query(sql: str, dialect: str) -> str:
    """Normalize the handful of dialect-specific functions/operators the call
    sites still emit in SQLite syntax. No-op for SQLite."""
    if dialect != "postgres":
        return sql
    # case-insensitive LIKE / equality / order
    sql = re.sub(r"\bLIKE\s+(\$\d+|\?)\s+COLLATE\s+NOCASE", r"ILIKE \1", sql, flags=re.I)
    sql = re.sub(r"(\b\w+)\s*=\s*(\$\d+|\?)\s+COLLATE\s+NOCASE", r"lower(\1) = lower(\2)", sql, flags=re.I)
    sql = re.sub(r"ORDER BY\s+(\w+)\s+COLLATE\s+NOCASE", r"ORDER BY lower(\1)", sql, flags=re.I)
    # day bucketing: strftime('%Y-%m-%d', col, 'unixepoch') -> to_char(...)
    sql = re.sub(
        r"strftime\(\s*'%Y-%m-%d'\s*,\s*(\w+)\s*,\s*'unixepoch'\s*\)",
        r"to_char(to_timestamp(\1) AT TIME ZONE 'UTC', 'YYYY-MM-DD')",
        sql,
        flags=re.I,
    )
    # tag aggregation
    sql = re.sub(r"GROUP_CONCAT\(\s*(\w+)\s*,\s*','\s*\)", r"string_agg(\1, ',')", sql, flags=re.I)
    return sql


def to_pg_ddl(sql: str) -> str:
    """Translate the SQLite SCHEMA/INDEXES DDL to Postgres."""
    sql = re.sub(
        r"INTEGER PRIMARY KEY AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        sql,
    )
    sql = re.sub(r"\bBLOB\b", "BYTEA", sql)
    # SQLite REAL is 8-byte double; Postgres REAL is 4-byte float4 (would round
    # 0.4 -> 0.40000000596). Use DOUBLE PRECISION to match SQLite.
    sql = re.sub(r"\bREAL\b", "DOUBLE PRECISION", sql)
    return sql


# ---- helpers shared by both backends ----------------------------------------

class _FetchMixin:
    async def execute(self, sql: str, params: "tuple | list" = ()):  # overridden
        raise NotImplementedError

    async def commit(self) -> None:  # overridden by each backend
        raise NotImplementedError

    async def rollback(self) -> None:  # overridden by each backend
        raise NotImplementedError

    @asynccontextmanager
    async def transaction(self):
        """Atomic unit of work: commit on clean exit, roll back on any exception.

        Multi-statement mutations (e.g. truncate-then-regenerate) must be all-or
        -nothing. Without the rollback, a statement that raises midway leaves the
        partial writes pending on the shared connection, and the NEXT request's
        ``commit()`` would silently flush them — a cross-request corruption. Use::

            async with db.transaction():
                await db.execute(...)   # delete
                await db.execute(...)   # insert

        On SQLite (the single shared aiosqlite connection) this is a real BEGIN/
        COMMIT/ROLLBACK. On the Postgres backend ``commit``/``rollback`` are the
        documented autocommit no-ops (per-statement) until the connection-pool
        refinement in docs/SCALING.md lands.
        """
        try:
            yield self
        except BaseException:
            await self.rollback()
            raise
        else:
            await self.commit()

    async def fetch_one(self, sql: str, params: "tuple | list" = ()) -> Row | None:
        cur = await self.execute(sql, params)
        return await cur.fetchone()

    async def fetch_all(self, sql: str, params: "tuple | list" = ()) -> list[Row]:
        cur = await self.execute(sql, params)
        return list(await cur.fetchall())

    async def fetch_val(
        self, sql: str, params: "tuple | list" = (), default: Any = None
    ) -> Any:
        row = await self.fetch_one(sql, params)
        return row[0] if row is not None else default


# ---- SQLite backend (default) -----------------------------------------------

class Database(_FetchMixin):
    def __init__(self, conn: aiosqlite.Connection, dialect: str = "sqlite") -> None:
        self._conn = conn
        self.dialect = dialect

    async def execute(self, sql: str, params: "tuple | list" = ()) -> aiosqlite.Cursor:
        return await self._conn.execute(sql, params)

    async def executemany(self, sql: str, seq_of_params) -> aiosqlite.Cursor:
        return await self._conn.executemany(sql, seq_of_params)

    async def executescript(self, script: str) -> Any:
        return await self._conn.executescript(script)

    async def commit(self) -> None:
        await self._conn.commit()

    async def rollback(self) -> None:
        await self._conn.rollback()

    async def close(self) -> None:
        await self._conn.close()

    def __getattr__(self, name: str) -> Any:
        if name == "_conn":
            raise AttributeError(name)
        return getattr(self._conn, name)

    async def insert(self, sql: str, params: "tuple | list" = ()) -> int:
        cur = await self._conn.execute(sql, params)
        return int(cur.lastrowid)


# ---- Postgres backend (asyncpg) ---------------------------------------------

class _PgCursor:
    """Buffered result so call sites can ``await cur.fetchone()/fetchall()`` just
    like aiosqlite. asyncpg Records support positional indexing (``row[0]``)."""

    def __init__(self, rows: list) -> None:
        self._rows = rows

    async def fetchone(self):
        return self._rows[0] if self._rows else None

    async def fetchall(self):
        return self._rows


class PostgresDatabase(_FetchMixin):
    def __init__(self, pool, acquire_timeout: float = 30.0) -> None:
        self._pool = pool
        self._acquire_timeout = acquire_timeout
        self.dialect = "postgres"
        # The (connection, owning-task) bound to the CURRENT task while inside
        # transaction(); None outside one (each statement then autocommits on a
        # pooled conn). ContextVars are task-local, so concurrent requests don't
        # see each other's bound connection; the owning-task tag additionally
        # rejects using one task's transaction connection from another task.
        self._bound: contextvars.ContextVar = contextvars.ContextVar(
            "pg_bound_conn", default=None
        )

    def _q(self, sql: str) -> str:
        return adapt_query(qmark_to_dollar(sql), "postgres")

    @asynccontextmanager
    async def _conn(self):
        """The bound transaction connection if inside one, else a freshly
        acquired pooled connection for a single autocommit statement.

        A bound connection may only be used from the task that opened the
        transaction: asyncpg forbids concurrent ops on one connection, so a
        ``gather`` of db ops or a db-touching child task inside a ``transaction()``
        would corrupt it — we raise a clear error instead."""
        bound = self._bound.get()
        if bound is not None:
            conn, owner = bound
            if owner is not asyncio.current_task():
                raise RuntimeError(
                    "concurrent/cross-task DB op inside transaction(): the bound "
                    "connection must not be used from another task (no asyncio.gather "
                    "of db ops, and no db-touching child task, inside the block)"
                )
            yield conn
        else:
            async with self._pool.acquire(timeout=self._acquire_timeout) as conn:
                yield conn

    async def execute(self, sql: str, params: "tuple | list" = ()) -> _PgCursor:
        q = self._q(sql)
        async with self._conn() as conn:
            rows = await conn.fetch(q, *params)
        return _PgCursor(rows)

    async def executemany(self, sql: str, seq_of_params) -> None:
        q = self._q(sql)
        data = [tuple(p) for p in seq_of_params]
        async with self._conn() as conn:
            await conn.executemany(q, data)

    async def executescript(self, script: str) -> None:
        # asyncpg's simple-query protocol (no args) runs multi-statement scripts.
        async with self._conn() as conn:
            await conn.execute(script)

    @asynccontextmanager
    async def transaction(self):
        """Real atomic unit on Postgres: acquire one pooled connection, bind it
        to this task, and run a BEGIN/COMMIT/ROLLBACK around the block. A nested
        ``transaction()`` on the same task joins the outer unit (no inner BEGIN),
        so a failure anywhere unwinds the whole thing."""
        if self._bound.get() is not None:
            yield self  # already in a transaction on this task → join it
            return
        async with self._pool.acquire(timeout=self._acquire_timeout) as conn:
            token = self._bound.set((conn, asyncio.current_task()))
            try:
                async with conn.transaction():
                    yield self
            finally:
                self._bound.reset(token)

    async def commit(self) -> None:
        # Atomicity comes from transaction(); a bare execute() already autocommits
        # on its pooled connection, so commit() outside a transaction is a no-op
        # (and inside one the real COMMIT happens when the block exits).
        return None

    async def rollback(self) -> None:
        return None

    async def close(self) -> None:
        await self._pool.close()

    async def insert(self, sql: str, params: "tuple | list" = ()) -> int:
        q = self._q(sql) + " RETURNING id"
        async with self._conn() as conn:
            row = await conn.fetchrow(q, *params)
        return int(row[0])


def is_postgres_url(target: str) -> bool:
    return target.startswith("postgres://") or target.startswith("postgresql://")
